hCaptcha/hmt-escrow

.travis.yml

Uses secure password for deploying new version to PyPI whenever we push new tags to master. 
Resolves #5

Deploy new version to pypi when new tags are pushed

---

basemodels/__init__.py
test.py

Part of the work on https://github.com/IntuitionMachines/hmt-servers/issues/1308

add capability for translations in answers

---

CONTRIBUTING.md
README.md
docker-compose.yaml

saw some old stuff lying around

fix the contributing doc link

---

.travis.yml
README.md
setup.py

- Adds some docs around how to make sure a deploy occurs via travis
- Gets it working as intended (broken before)

Some build+deploy fixes, and notes on how to deploy

---

api/__init__.py
test.py

This PR:
- Does "under the roof" amount convertion to HMT with a multiplication of 100
- Rounds `job task bid price` to 2 digits (to conform to 100 multiplication)
- Adds basic tests to test out the convertion
Closes #23

HMT amount job convertion

---

setup.py

Bump float conversion as a minor patch

---

api/__init__.py
basemodels/__init__.py
test.py

1. Modify the manifest to include oracle_fee field
2. Take the value from manifest and initialize the contract with the given fee
3. Tests fee distribution with initialized fee
Closes #29

Add adjustable oracle fees

---

basemodels/__init__.py
setup.py

Add bounding box request types to list of allowed types. Fixes #46

Update allowed request_type

---

basemodels/__init__.py
setup.py
test.py

Closes https://github.com/hCaptcha/hmt-escrow/issues/55
Also adds some additional fields that I didn't see in the manifest compared to the spec in hmt-servers
Still needs to be updated in hmt-servers after build / push

add request_config field

---

basemodels/__init__.py
setup.py
test.py

Related to this comment: https://github.com/hCaptcha/hcaptcha-v1/issues/231#issuecomment-466197877
@e271828- @todicus lmk if you think this is reasonable

set default requester_restricted_answer_set for image_label_area_select

---

api/__init__.py

Partially closes https://github.com/hCaptcha/hmt-escrow/issues/65

Correct comment

---

setup.py
yarn.lock

Replaces Alex's PR because travis was being a punk

Bump lock file

---

hmt_escrow/job.py
setup.py

Add intermediate results and hash as public getter functions.

Add public intermediates

---

Dockerfile

should fix build, doesnt need a deploy to pypi

use bionic

---

setup.py

bump version specified in setup.py

---

contracts/Escrow.sol
setup.py

No reason why we shouldn't support cancel for partial contracts

Support cancel

---

package.json
setup.py
truffle.js
yarn.lock

Fixes sec vulnerability with `diff` by bumping truffle.

Bump diff sec vulnerability

---

hmt_escrow/eth_bridge.py
hmt_escrow/job.py
setup.py

Closes #113 
Fix hmt_escrow tests and add possibility to define hmtoken addr as an argument

Add hmtoken addr as an argument

---

Dockerfile
contracts/Escrow.sol
hmt_escrow/job.py
setup.py
test/Escrow.js

Add the launcher of the contract to the escrow itself.

Add launcher

---

Pipfile
Pipfile.lock
setup.py

Version ipfsapi 0.4.3 was a breaking change. Update config.py to 0.4.4

fix breaking ipfsapi version

---

contracts/Escrow.sol
contracts/SafeMath.sol
truffle.js

Add low-hanging vulnerabilities ran with MythX

---

.eslintrc.json
contracts/Escrow.sol
docker-compose.yml
test/Escrow.js
test/utils/helpers.js

In the current implementation of some tests, when checking if the contract errors some errors are checked incorrectly. This branch fixes that logic and checks specific error messages
- Abstracted the error logic into a util
- Updated test to fail correctly
- Update formatting of tests to be more readable
closes #130

fix: update tests to check error messages

---

contracts/Escrow.sol
hmt_escrow/job.py
setup.py

Closes #162 
First part of making sure multiple wallets can store results and do bulk payments.
Also set rec and rep oracle as "trusted handlers" in setup time by default.

Feat 162 raffle payout and results

---

hmt_escrow/storage.py
setup.py

Seems we can do this per the docs: https://ipfs.io/ipns/12D3KooWEqnTdgqHnkkwarSrJjeMP2ZJiADWLYADaNvUb6SQNyPF/docs/http_client_ref.html?highlight=cat#the-api-client

try to timeout download in cat

---

contracts/Escrow.sol
setup.py
test/Escrow.js

Add msg.sender as a trusted handler. Refactor tests, should fix issues with

Fix gas payer trusted

---

Pipfile
Pipfile.lock
hmt_escrow/storage.py
setup.py

Finally fixed and merged in 0.4.13.2 version: https://github.com/ipfs-shipyard/py-ipfs-http-client/pull/206

Use rbval ipfs

---

hmt_escrow/job.py
setup.py

Helps debugging underlying issues a bit more.

Fix add more logging

---

hmt_escrow/job.py
setup.py

Fix 174 raffling creds

---

.gitignore
Pipfile
Pipfile.lock
bin/wait_then_run
docker-compose.yml
hmt_escrow/storage.py
setup.py

Closes #180 
Add an option for S3 storage for download and upload. Doesn't introduce an API change since we default to s3.

Add an option for s3 storage

---

hmt_escrow/job.py
setup.py

Add s3 support to uploads

---

bin/wait_then_run
docker-compose.yml
hmt_escrow/job.py
setup.py

Fix 186 noisy raffling

---

docker-compose.yml
hmt_escrow/job.py
setup.py

Closes #188 
1. Use an internal function to keep the code DRY
2. Add raffling to remaining functions that perform a transaction

Add raffling to the remaining transaction functions

---

hmt_escrow/eth_bridge.py
hmt_escrow/job.py
hmt_escrow/storage.py

Disable doc tests but return the comments

return docs

---

contracts/Escrow.sol
hmt_escrow/eth_bridge.py
hmt_escrow/job.py
hmt_escrow/storage.py
sphinx-documentation/source/conf.py
test/Escrow.js
test/EscrowFactory.js

Measure gas

---

contracts/Escrow.sol
hmt_escrow/eth_bridge.py
hmt_escrow/job.py
hmt_escrow/storage.py
sphinx-documentation/source/conf.py
test/Escrow.js

Reduce Escrow gas usage

---

contracts/Escrow.sol

Tests seem to pass if this was the kind of change you meant

Add address check for trusted function calls.

---

setup.py

I forgot in the previous commit to add a new version number in setup.py.

Add new version number in setup.py

---

hmt_escrow_js/.eslintrc.yml
hmt_escrow_js/ETHInterface.js
hmt_escrow_js/Job.js
hmt_escrow_js/package.json
hmt_escrow_js/yarn.lock

1. Linter added
2. Fixed vars
Fixes changes mentioned in https://github.com/hCaptcha/hmt-escrow/pull/230
related to issue https://github.com/hCaptcha/hmt-escrow-form/issues/2

Linter added to JS Package

---

contracts/Escrow.sol
package-lock.json
test/Escrow.js

And clean the contract on the whole.

Transfer tokens when aborting escrow
