test.py
Cleans up a bunch of test log messages from sub projects such as:
```
DEBUG:web3.RequestManager:Making request. Method: eth_call
DEBUG:web3.providers.HTTPProvider:Making request HTTP. URI: http://ganache:8545, Method: eth_call
DEBUG:web3.providers.HTTPProvider:Getting response HTTP. URI: http://ganache:8545, Method: eth_call, Response: {'id': 181, 'jsonrpc': '2.0', 'result': '0x0000000000000000000000000000000000000000000000000000000000000001'}
DEBUG:web3.RequestManager:Making request. Method: eth_getBlockByNumber
```
=> reduce the test verbosity

Pipfile, Pipfile.lock, setup.py
This PR updates the evm to the latest working and makes the rest of the dependencies work together with it.
=> Fix dependencies to work with py-evm 0.2.0a34

api/__init__.py, api/eth_bridge.py, hmt.sol, setup.py, test.py
This PR:
- Uses our actual HMToken and HMTokenInterface from `hmt-token` repo
- Adds support for bulk payments on the contract level
- Adds support for bulk payments on the python api level
Closes #42 
Closes #41
=> Add support for bulk payout in the API

api/__init__.py, hmt.sol, setup.py, test.py
Adds refund functionality to the contract level that returns the funds to the contract initiator but doesn't kill the contract. Adds a simple test to test that contract status is updated correctly.
Closes #51
=> Add refund

hmt_escrow/job.py, setup.py
Apparently the timeout decorator didn't work as planned in the Job initialization. This removes it from the process of polling for the `manifest_url` and `manifest_hash`. In theory we should never enter an infinite loop if we access an existing job because they would always have a manifest hash / url.
=> Remove timeout decorator from polling of manifest hash and url

hmt_escrow/job.py, setup.py
Adds some convenience functions for third parties that don't require the initialization of the Job class:
- `status`
- `manifest_url`
- `manifest_hash`
=> Add public getters

bin/ci, bin/wait_then_run, docker-compose.yml, hmt_escrow/eth_bridge.py, hmt_escrow/job.py, hmt_escrow/kvstore_abi.py
This logic should live here instead of hmt-servers or loader.
Note: renames `get_pk_from_address` to `get_pub_key_from_addr` and adds a corresponding SET function: `set_pub_key_at_addr`
Fixes #86
=> add get_pk_from_address to eth_bridge

contracts/Escrow.sol
The modifier of finalizePayouts was changed by public to internal in order to prevent a possible dos attack on Oracles fees like described by issue #140 
closes #140
=>  finalizePayouts from public to internal

hmt_escrow/eth_bridge.py, hmt_escrow/job.py, hmt_escrow/storage.py
If doctests fail, this raises an error. Fixes CI.
=> Raise doctest on error for CI

setup.py
Dev packages are not necessary for downstream consumers
=> remove dev deps from package details

hmt_escrow/job.py, setup.py
Closes #155 
Added initial version of the multi-cred support. Existing API doesn't break, adds only an enhancement with `multi_credentials`.
Design decisions:
1. Use a list of tuples for easy looping when raffling new credentials
2. Just walk the list instead of taking a random when raffling new credentials. Gave it some thought and this felt a lot simpler and more deterministic. Am I missing something?
3. Added new tests to test out that raffling indeed works and launches the contract as intended to the blockchain
=> Add multi-cred support

contracts/Escrow.sol, hmt_escrow/job.py, setup.py, test/Escrow.js
Closes #149 
Lets us specify separate cancelers on launch time, so called "trusted handlers". These will be able to abort jobs on behalf of the launcher.
=> Add trusted handlers

Pipfile, Pipfile.lock, docker-compose.yml, hmt_escrow/storage.py, setup.py
This is a drop in replacement that contains a ipfs http timeout feature thats more reliable than the timeout decorator, going to get rid of it in jobrunner too
=> Use ipfshttpclient

contracts/Escrow.sol, contracts/EscrowFactory.sol, hmt_escrow/job.py, setup.py, test/Escrow.js, test/EscrowFactory.js
Closes #172 
Closes #161
1. Adds raffling on setup
2. By default adds our multi creds to the contract when we launch the contract
Benefits:
1. We should not see `contract did not get funded` anymore as we used to.
2. Make job loading 15 seconds faster (per job load)
=> Add raffling to setup, make job loading faster

Dockerfile, hmt_escrow/eth_bridge.py, setup.py
Closes #190 
We've been getting 
```
Error: 429 Client Error: Too Many Requests for url: https://rinkeby.infura.io
```
recently due to `waitForTransactionReceipt` polling every 0.1 seconds.
Since it takes approx 15 seconds to write to Ethereum, this PR adds the poll latency to 5 seconds.
=> Add poll latency so we don't unnecessarily poll too frequently

MANIFEST.in
It seems the new hmt-escrow package fails to install with pipenv. This is because of two missing `*` in the MANIFEST.in file. I have locally built and successfully installed the package after these changes.
A new release should be deployed.
=> Fix breaking when installing new dist

.dockerignore, .travis.yml, Dockerfile, Pipfile, Pipfile.lock, bin/ci, docker-compose.yml, hmt_escrow/eth_bridge.py, hmt_escrow/job.py, package.json, requirements.txt, setup.py
Updated hmt-escrow to use the latest versions of web3, py-evm and p2p (commonly referred to recently as 'trinity') needed for Python3.8. Revert to using pipenv.
=> Update web3 and py-evm using trinity

README.md, setup.py
When installing hmt-escrow from PyPi, there seems to be lots of issues with master tagged deps in setup.py.
=> Remove deps with link from setup.py

hmt_escrow/eth_bridge.py
**Changes**
- edited `get_w3()` to support WSS endpoints set in HMT_ETH_SERVER
- Technically, this will now support any endpoints that are supported by `web3`'s `AutoProvider`, more below
**Reasoning**
- Fixes #236 
**Motivation**
- Instead of using a parameter, we can utilize a helper function available in `web3.providers.auto` called `load_provider_from_uri` (https://github.com/ethereum/web3.py/blob/master/web3/providers/auto.py#L46-L62) which will return the proper `Provider` to be inserted into `Web3(provider)`. This also adds support for IPC if ever needed
=> Add WSS support to get_w3() 

package.json, private-provider.js, truffle.js
This PR adds the necessary changes so that the Truffle script works for deploy the contracts into Moonbase Alpha, the Moonbeam TestNet.
Currently, we don't support the usage of `hd-wallet-provider`, as one of the dependencies that it uses has "baked-in" the chain Id of known Ethereum Networks. Thus when you point it to Moonbase Alpha, the Chain Id is not recognized and so it is not included in the tx, making the signature invalid. Consequently, the transaction is rejected. We are currently working with Truffle to solve this issue.
In the meantime, we've programed a provider (file `private-provider.js`) which uses the [web3-provider-engine](https://github.com/MetaMask/web3-provider-engine.git) and [ethereumjs-wallet](https://github.com/ethereumjs/ethereumjs-wallet) libraries. For this …
=> Added Moonbeam compatibility
